import './globals.css'
import type { Metadata } from 'next'
import Nav from './components/Nav'
import { getServerSession } from 'next-auth' // look for is the user is sign in
import { authOptions } from '@/pages/api/auth/[...nextauth]'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // fetch the user
  const session = await getServerSession(authOptions)
  //console.log(session)


  return (
    <html>
      <body className='mx-64 bg-slate-900 text-white'>
        <Nav user={session?.user} expires={session?.expires as string} />
        {children}
        </body>
    </html>
  )
}
